/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EmployeeRouteImport } from './routes/employee'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin-dashboard'
import { Route as AuthenticatedEmployeeDashboardRouteImport } from './routes/_authenticated/employee-dashboard'
import { Route as ApiUsersCreateRouteImport } from './routes/api/users/create'
import { Route as ApiUsersDeleteRouteImport } from './routes/api/users/delete'
import { Route as ApiUsersUpdateRouteImport } from './routes/api/users/update'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeRoute = EmployeeRouteImport.update({
  id: '/employee',
  path: '/employee',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin-dashboard',
    path: '/admin-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployeeDashboardRoute =
  AuthenticatedEmployeeDashboardRouteImport.update({
    id: '/employee-dashboard',
    path: '/employee-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiUsersCreateRoute = ApiUsersCreateRouteImport.update({
  id: '/api/users/create',
  path: '/api/users/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersDeleteRoute = ApiUsersDeleteRouteImport.update({
  id: '/api/users/delete',
  path: '/api/users/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersUpdateRoute = ApiUsersUpdateRouteImport.update({
  id: '/api/users/update',
  path: '/api/users/update',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/employee': typeof EmployeeRoute
  '/admin-dashboard': typeof AuthenticatedAdminDashboardRoute
  '/employee-dashboard': typeof AuthenticatedEmployeeDashboardRoute
  '/api/users/create': typeof ApiUsersCreateRoute
  '/api/users/delete': typeof ApiUsersDeleteRoute
  '/api/users/update': typeof ApiUsersUpdateRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/employee': typeof EmployeeRoute
  '/admin-dashboard': typeof AuthenticatedAdminDashboardRoute
  '/employee-dashboard': typeof AuthenticatedEmployeeDashboardRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/users/create': typeof ApiUsersCreateRoute
  '/api/users/delete': typeof ApiUsersDeleteRoute
  '/api/users/update': typeof ApiUsersUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/employee': typeof EmployeeRoute
  '/_authenticated/admin-dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/employee-dashboard': typeof AuthenticatedEmployeeDashboardRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/users/create': typeof ApiUsersCreateRoute
  '/api/users/delete': typeof ApiUsersDeleteRoute
  '/api/users/update': typeof ApiUsersUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/employee'
    | '/admin-dashboard'
    | '/employee-dashboard'
    | '/api/users/create'
    | '/api/users/delete'
    | '/api/users/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/auth'
    | '/employee'
    | '/admin-dashboard'
    | '/employee-dashboard'
    | '/'
    | '/api/users/create'
    | '/api/users/delete'
    | '/api/users/update'
  id:
    | '__root__'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/employee'
    | '/_authenticated/admin-dashboard'
    | '/_authenticated/employee-dashboard'
    | '/_authenticated/'
    | '/api/users/create'
    | '/api/users/delete'
    | '/api/users/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  EmployeeRoute: typeof EmployeeRoute
  ApiUsersCreateRoute: typeof ApiUsersCreateRoute
  ApiUsersDeleteRoute: typeof ApiUsersDeleteRoute
  ApiUsersUpdateRoute: typeof ApiUsersUpdateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee': {
      id: '/employee'
      path: '/employee'
      fullPath: '/employee'
      preLoaderRoute: typeof EmployeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-dashboard': {
      id: '/_authenticated/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employee-dashboard': {
      id: '/_authenticated/employee-dashboard'
      path: '/employee-dashboard'
      fullPath: '/employee-dashboard'
      preLoaderRoute: typeof AuthenticatedEmployeeDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/users/create': {
      id: '/api/users/create'
      path: '/api/users/create'
      fullPath: '/api/users/create'
      preLoaderRoute: typeof ApiUsersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/delete': {
      id: '/api/users/delete'
      path: '/api/users/delete'
      fullPath: '/api/users/delete'
      preLoaderRoute: typeof ApiUsersDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/update': {
      id: '/api/users/update'
      path: '/api/users/update'
      fullPath: '/api/users/update'
      preLoaderRoute: typeof ApiUsersUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedEmployeeDashboardRoute: typeof AuthenticatedEmployeeDashboardRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedEmployeeDashboardRoute: AuthenticatedEmployeeDashboardRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  EmployeeRoute: EmployeeRoute,
  ApiUsersCreateRoute: ApiUsersCreateRoute,
  ApiUsersDeleteRoute: ApiUsersDeleteRoute,
  ApiUsersUpdateRoute: ApiUsersUpdateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
